development:
  adapter: postgresql
  encoding: unicode
  database: eightball_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: eightball_test
  pool: 5
  username: postgres
  password: postgres
